config/routes.rb
Rails.application.routes.draw do
  root :to => "recipes#new"
  devise_for :users
  resources :recipes
  resources :events
  get 'tags/:tag', to: 'events#index', as: :tag

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :organizers, class_name: "User"
  has_many :taggings
  has_many :tags, through: :taggings
  attr_accessor :all_tags
  extend FriendlyId
  friendly_id :title, use: :slugged
  def slug_candidates
    [
      :title,
      [:title,:location]
    ]
  end
  def all_tags
    tags.map(&:name).join(",")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).events
  end

  def self.tag_counts
    Tag.select("tags.name,count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end

end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
  has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :food_type
  belongs_to :food_preference
  belongs_to :cuisine
  DIFFICULTY=%w(Easy Medium Hard)
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :events, through: :taggings
  def all_tags=(names)
    self.tags = names.split(",").map do |t|
      Tag.where(name: t.strip).first_or_create!
    end
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "application"
  before_action :sidebar_values
  def sidebar_values
    @food_preferences = FoodPreference.all
    @food_types = FoodType.all
    @cuisines = Cuisine.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :event_owner!, only:[:edit,:update,:destroy]

  # GET /events
  # GET /events.json
  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end  
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def event_owner!
      authenticate_user!
      if @event.organizer_id != current_user.id
        redirect_to events_path
        flash[:notice] = 'You do not have enough permissions to do this'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :location, :agenda, :address, :organizer_id,:all_tags)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create,:update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    # byebug
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :agenda %><br>
    <%= f.text_area :agenda %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <!-- <div class="field">
    <%= f.label :organizer_id %><br>
    <%= f.number_field :organizer_id %>
  </div> -->
  
  <div class="field">
  all_tags
    <%= f.label :all_tags,"List All Tag, separate each tag by a comma" %><br>
    <%= f.text_field :all_tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organizer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= l event.start_date, :format => :date_format %></td>
        <td><%= l event.start_date, :format => :date_format %></td>
        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= event.all_tags.map{ |t| link_to t, tag_path(t)}.join(',') %></td>
        <td><%= event.organizer_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @event.agenda %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @event.organizer_id %>
</p>

<p>
  <%=raw event.tags.map(&:name).map{ |t| t}.join(',') %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_aside.html.erb
<div class="col-md-2 text-center">
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Food Preferences
        </div>
        <% @food_preferences.each do |fp| %>
            <p><%= fp.name%></p>
        <%end%>
      </div>
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Food Type
        </div>
        <% @food_types.each do |ft| %>
            <p><%= ft.name%></p>
        <%end%>
      </div>
      <div class="panel panel-primary" id="panels">
        <div class="panel-heading">Cuisine
        </div>
        <% @cuisines.each do |c| %>
            <p><%= c.name%></p>
        <%end%>
      </div>
    </div>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default ">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Project name</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Recipes',recipes_path %></li>
        <li><%= link_to 'Events',events_path %></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">Dropdown <span class="caret"></span></a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%=link_to "#{current_user.email}" %></li>
            <li class="active"><%= link_to "Logout",destroy_user_session_path, method:
:delete %></li>
            <%else%>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li class="active"><%= link_to "SignUp",new_user_registration_path%></li>
            <%end%>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_hearder.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Project name</a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Recipes",recipes_path %></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">Dropdown <span class="caret"></span></a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%=link_to "#{current_user.email}" %></li>
            <li class="active"><%= link_to "Logout",destroy_user_session_path%></li>
            <%else%>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li class="active"><%= link_to "SignUp",new_user_registration_path%></li>
            <%end%>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div class="container">
  <div class="row">
    <%= render "layouts/aside" %>
    <div class="col-md-9">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cooking_time %><br>
    <%= f.text_field :cooking_time %>
  </div>
  <div class="field">
    <%= f.label :difficulty_level %><br>
    <%= f.select :difficulty_level, Recipe::DIFFICULTY,{} %>
  </div>
  <div class="field">
    <%= f.label :food_type_id %><br>
    <%= f.select(:food_type_id, options_from_collection_for_select(FoodType.all, :id,:name), {:prompt => 'Please Choose'}) %>
  </div>
  <div class="field">
    <%= f.label :food_preference_id %><br>
    <%= f.select(:food_preference_id,options_from_collection_for_select(FoodPreference.all,:id, :name), {:prompt => 'Please Choose'}) %>
  </div>
  <div class="field">
    <%= f.label :cuisine_id %><br>
    <%= f.select(:cuisine_id,options_from_collection_for_select(Cuisine.all, :id,:name), {:prompt => 'Please Choose'}) %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<% if user_signed_in? %>
<td><%= link_to 'Edit', edit_recipe_path(@recipes),:class=>"btn btn-success btn-small"%></td>
<td><%= link_to 'Delete', @recipe, method: :delete,data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-small" %></td>
<%end%>

<p id="notice"><%= notice %></p>

<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cooking time</th>
      <th>Difficulty level</th>
      <th>Food type</th>
      <th>Food preference</th>
      <th>Cuisine</th>
      <th>Ingredients</th>
      <th>Procedure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <%= byebug %>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.food_type.name %></td>
        <td><%= recipe.food_preference.name %></td>
        <td><%= recipe.cuisine.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @recipe.food_type_id %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= @recipe.food_preference_id %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine_id %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>